// Code generated by MockGen. DO NOT EDIT.
// Source: guid.go

// Package mock_guid is a generated GoMock package.
package mock_guid

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGuid is a mock of Guid interface.
type MockGuid struct {
	ctrl     *gomock.Controller
	recorder *MockGuidMockRecorder
}

// MockGuidMockRecorder is the mock recorder for MockGuid.
type MockGuidMockRecorder struct {
	mock *MockGuid
}

// NewMockGuid creates a new mock instance.
func NewMockGuid(ctrl *gomock.Controller) *MockGuid {
	mock := &MockGuid{ctrl: ctrl}
	mock.recorder = &MockGuidMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuid) EXPECT() *MockGuidMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockGuid) New() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(string)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockGuidMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockGuid)(nil).New))
}
